### ISSUE TITLE
Can’t resolve aws-sdk/clients/lambda

### ISSUE THREAD

**Issue by Darlington02** [OpenZeppelin/defender-client#137]
Issues with using the defender relay client npm package with nextjs in browser

the error says

```
error - ./node_modules/defender-base-client/lib/autotask/index.js:7:0
Module not found: Can't resolve 'aws-sdk/clients/lambda'
Import trace for requested module:
./node_modules/defender-relay-client/lib/autotask/index.js
./node_modules/defender-relay-client/lib/relayer.js
./node_modules/defender-relay-client/lib/ethers/signer.js
./node_modules/defender-relay-client/lib/ethers/index.js
./pages/index.js
```

Though i solved the issue by using autotasks, for a very simple project, is there any work around to make this work in the browser?

**Comment by zeljkoX** [comment]
Hi @Darlington02 

This package is not designed to be used in a browser environment. 
This package requires sensitive API KEYS and by using it in a browser they would be public.

Depending on how You use Next.js, option is to use [Next.js API routes](https://nextjs.org/docs/api-routes/introduction) as they are not bundled as part of FE code.

**Comment by Darlington02** [comment]
Oh right, API routes sounds interesting would definitely check that out.

Thank you
