### ISSUE TITLE
Relay API client throws non-error objects 

### ISSUE THREAD

**Issue by cbm-egoubely** [OpenZeppelin/defender-client#139]
When using `RelayClient` or sending transactions with `DefenderRelaySigner`, errors are thrown as non-error objects. 

For example, if your account does not have enough MATIC and you try to send a transaction with `RelayerClient.sendTransaction()`, an object with the following structure will be thrown:

```json
{
  "response": {
    "status": 400,
    "statusText": "Bad Request",
    "data": {
      "message": "Insufficient funds: 0.0194178065148 MATIC required but 0.0 MATIC are available."
    }
  },
  "message": "Request failed with status code 400",
  "request": {
    "path": "/txs",
    "method": "POST"
  }
}
```
The thrown object does not extend the standard `Error` class.

First, this makes debugging and monitoring sometimes confusing. For example Sentry will display those errors as `Non-Error exception captured with keys: message, request, response`. 
When uncaught in AWS Lambda, it will be logged in CloudWatch like this:
```json
{
  "errorType": "object",
  "errorMessage": "[object Object]",
  "trace": []
}
```

Also, we need to be able to automate the recovery of failures such as HTTP 402s (quota exceeded) or some HTTP 400s (insufficient founds) but the SDK makes it difficult to create our own errors.

The problem comes from the Axios response interceptor you use: 
```typescript
  instance.interceptors.response.use(
    (response) => response.data,
    (error) =>
      Promise.reject({
        response: pick(error.response, 'status', 'statusText', 'data'),
        message: error.message,
        request: pick(error.request, 'path', 'method'),
      }),
  );
```
https://github.com/OpenZeppelin/defender-client/blob/master/packages/base/src/api/api.ts#L15-L23

The minimum would be to turn the object your throw `{ response: pick(error.response, 'status', 'statusText', 'data'), message: error.message, request: pick(error.request, 'path', 'method') }` into an instance of `Error`.

Ideally, the SDK should throw errors implementing or extending a common `Error` class (e.g.`RelayApiResponseError`) and export it so we can extend it to create our custom errors, and the API error response codes should be documented.

**Comment by BjMrq** [comment]
Hi @cbm-egoubely , thanks for reaching out!
It does seem that we are not returning a standardized Error and we would like to change that.
We will be updating the version with a fix for this soon.

**Comment by BjMrq** [comment]
It as been addressed here and will soon be available in the package https://github.com/OpenZeppelin/defender-client/commit/a6029410ebaf347d0ba5e71d06e39d4761fd514d
