### ISSUE TITLE
Retry authentication call to Cognito if rate limit error occurs

### ISSUE THREAD

**Issue by mok0230** [OpenZeppelin/defender-client#143]
We had an issue recently where a call to Cognito got throttled. If this occurs, we should retry the call.

The authenticate function that needs retry logic is here: https://github.com/OpenZeppelin/defender-client/blob/9b155e8d8b412b59abf3e8045965fdde403b73fc/packages/base/src/api/auth.ts

**Comment by mverzilli** [comment]
Would you add any references you have to this diagnostic? Support requests, cloudwatch logs, etc. It would help whoever eventually tackles this properly test

**Comment by mok0230** [comment]
Sign in throttles should be shown on [this chart](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#metricsV2:graph=~(metrics~(~(~'AWS*2fCognito~'SignInThrottles~'UserPool~'us-west-2_iLmIggsiy~'UserPoolClient~'1bpd19lcr33qvg5cr3oi79rdap)~(~'.~'SignInSuccesses~'.~'.~'.~'.))~view~'timeSeries~stacked~false~region~'us-west-2~stat~'Sum~period~300~start~'-PT72H~end~'P0D);query=~'*7bAWS*2fCognito*2cUserPool*2cUserPoolClient*7d*20cognito)/. If you include August 1 in the period, you will see some blue dots (throttles).

In assessing this situation, it does not appear we were anywhere near our quota, yet the requests got throttled anyhow. For reference, we believe the main quota of concern is [Rate of UserAuthentication requests](https://us-west-2.console.aws.amazon.com/servicequotas/home/services/cognito-idp/quotas/L-026ADBA3) that would typically lead to a throttling (it was out highest Utliization % of all the candidate quotas, even though it was only 5%)
