### ISSUE TITLE
Sentinel `txCondition` omitted if `eventConditions` and `functionConditions` are `undefined`.

### ISSUE THREAD

**Issue by iantanwx** [OpenZeppelin/defender-client#149]
Gm, we have been trying to use `defender-sentinel-client` to create Sentinels programmatically. We only wish to monitor a given address for incoming transfers of `ETH`, and do not require `eventConditions` or `functionConditions`. Unfortunately, it looks like [`contructBlockSentinel`](https://github.com/OpenZeppelin/defender-client/blob/7a0a162e52e04f6a635f7d862a34b95bfe591d9d/packages/sentinel/src/api/index.ts#L171-L197) is dropping `txCondition` if no `eventConditions` or `functionConditions` are specified. 

This behaviour is unexpected and not consistent with creating a Sentinel by hand via the dashboard. At the moment we are planning to use autotask conditions as a workaround, but it is probably far better if the Defender team fixes the problem at the client level to start with.

**Comment by dylankilkenny** [comment]
@iantanwx thanks for reporting this issue to us, this indeed is a bug. I have created a PR to resolve it.
