### ISSUE TITLE
The Network type is not exported in the `defender-sentinel-client` package

### ISSUE THREAD

**Issue by manboy-eth** [OpenZeppelin/defender-client#169]
The Network type used here: https://github.com/OpenZeppelin/defender-client/blob/ecb9dd34d32db5dca56f26ce73f8bdb895431f5f/packages/sentinel/src/models/subscriber.ts#L24 is required for creating typed sentinel request, like this `const requestParameters: CreateSentinelRequest = `.

The problem is that the `Network` type is not exported for use from the `defender-sentinel-client` package. It is, therefore, difficult to create a type-safe CreateSentinelRequest when only having the `defender-sentinel-client` package installed (since it's only exported from the `defender-base-client`).

Perhaps the Network type could be reexported in the `defender-sentinel-client` package?

**Comment by BjMrq** [comment]
Hi @manboy-eth thanks for reporting this! `defender-base-client` should be included in all the client packages, maybe you could import the Network type from there?

**Comment by manboy-eth** [comment]
> Hi @manboy-eth thanks for reporting this! `defender-base-client` should be included in all the client packages, maybe you could import the Network type from there?

That works perfectly. Thank you! 
I thought I would have to explicitly import `defender-base-client` for that to work - I was clearly wrong.
