### ISSUE TITLE
defender-admin-client next release

### ISSUE THREAD

**Issue by olich97** [OpenZeppelin/defender-client#173]
Hello there 👋, 
many thanks for work you're doing here. 
I was wondering when the new version of the `defender-admin-client` package could be available to use? I was looking forward to start using [this newly added feature ](https://github.com/OpenZeppelin/defender-client/pull/170) to the admin apis 🚀
Thanks in advance and have a nice day :)

**Comment by BjMrq** [comment]
Hello @olich97 🙌
It has been released just now!

**Comment by olich97** [comment]
Hi @BjMrq 👋,
sorry to bother you again 🙏
I was wondering if it possible to retrive transaction data related to the proposal thought open zeppelin admin api.
I guess on Open Zeppelin Admin dashboard its possibile to view that information: dashboard ui uses` https://api.defender.openzeppelin.com/admin/contracts/{contractId}/proposals/{proposalId}` and in the response is present a transaction object (very useful for us) similar to:
```
"transaction": {
    "isSuccessful": true,
    "isExecuted": true,
    "data": "hex",
    "executionTxHash": "tx hash",
    "safe": {
      "txHash": "tx hash",
      "operationType": "call",
      "txGas": "0"
    },
    "to": "address",
    "confirmations": [
      {
        "owner": "address",
        "signature": "sig"
      },
      {
        "owner": "address",
        "signature": "sig"
      }
    ],
    "nonce": 11,
    "value": "0",
    "isReverted": false
  }
```
Do you know if it will be possible to obtain the same object using client api endpoint `https://defender-api.openzeppelin.com/admin/contracts/{contractId}/proposals/{proposalId}`?

Many thanks in advance 😀

**Comment by BjMrq** [comment]
Hey again @olich97 it should be included in one of the next releases 🏗️ !

**Comment by olich97** [comment]
> Hey again @olich97 it should be included in one of the next releases 🏗️ !

Cool! 😃 can you perhaps give me some hints on when its scheduled for?

**Comment by BjMrq** [comment]
Should be sometime this week!

**Comment by olich97** [comment]
Thanks @BjMrq. Looking forward to this 😃
