### ISSUE TITLE
Publish 1.49.0-rc to npm and/or fix install and build

### ISSUE THREAD

**Issue by haardikk21** [OpenZeppelin/defender-client#380]
Hey,

I'm trying to add a viem adapter to the relay client and forked this repo. Based on your README, it looks like you publish new versions of the packages to npm locally. 

The codebase was updated to 1.49 rc versions a week ago, and specifically the `defender-base-client`'s API and exports have changed from 1.48 to 1.49. 

However, `yarn install` on a fresh clone is failing due to not being able to find version 1.49. Your CI has been failing for a week as well.

Would love to urge you to publish that version and/or fix the install and build process otherwise. I'd love to add a viem adapter here, and am sure it'd be helpful for others too.

Thanks

**Comment by MCarlomagno** [comment]
Hi @haardikk21 thanks a lot for reaching out, I'm going to investigate the issue and let you know any updates

**Comment by MCarlomagno** [comment]
@haardikk21 we just released a new version of the package, let me know if you still have any issues.
Thanks!
