### ISSUE TITLE
Incomplete Package Content for @openzeppelin/defender-base-client:1.54.0 on NPM

### ISSUE THREAD

**Issue by 597800451** [OpenZeppelin/defender-client#467]
I've recently attempted to install the `@openzeppelin/defender-base-client` package from NPM, but I've encountered an issue.  Post-installation, the `node_modules/@openzeppelin/defender-base-client` directory only contains the `package. json` file, and the expected library files in the `lib` folder are missing.

This seems to indicate that the package published on NPM may be incomplete.  Could you please check if the package was published correctly?  Or is there a different procedure to follow for a complete installation?

Your assistance in resolving this matter would be greatly appreciated, as I am keen to utilize this package for my project.

Thank you for your time and effort.

Best regards,

![image](https://github.com/OpenZeppelin/defender-client/assets/5043738/aa3855b7-84bd-49ac-b5c1-17419c8a178a)

**Comment by tirumerla** [comment]
Hi @597800451 , thanks for bringing this to our attention. We published a new package and deprecated `1.54.0` if you could upgrade to `1.54.1` it should work as expected. Also i'm wondering if you have already tried using `defender-sdk-*-client` packages just wanted to let you know this will be our new client packages for defender 2.0 and also supports majpority of the defender 1.0 features.

**Comment by 597800451** [comment]
Hi, thank you for the quick response and the update. I will try upgrading to version 1.54.1 as you suggested. Also, I appreciate the information about the defender-sdk-*-client packages for Defender 2.0, and I will consider using them in my project. Thanks again for your assistance!
