### ISSUE TITLE
Relay client sign function returning different results for same message

### ISSUE THREAD

**Issue by codenutt** [OpenZeppelin/defender-client#58]
Could you should any light on what's going on behind the scenes of the relay's sign functionality? I can sign the same message multiple times and get a different result each time. Thanks!

**Comment by spalladino** [comment]
Hey @codenutt! All those are valid signatures. The ECDSA signing algorithm uses a random value as part of the signature process, which some libraries derive deterministically from the payload to sign (resulting in the same signature for the same payload every time), while others draw from an entropy source (resulting on different signatures for the same payload). Defender Relayers use AWS KMS under the hood, which uses the latter.

**Comment by spalladino** [comment]
Closing issue since the original question was answered

**Comment by brooklynbagel** [comment]
> Hey @codenutt! All those are valid signatures. The ECDSA signing algorithm uses a random value as part of the signature process, which some libraries derive deterministically from the payload to sign (resulting in the same signature for the same payload every time), while others draw from an entropy source (resulting on different signatures for the same payload). Defender Relayers use AWS KMS under the hood, which uses the latter.

If this is the case, how would one recover the address that generated the signature? As far I can tell, the API for signing using Relay does not return that random value, making it infeasible to check the key hosted on a relay signed the message.

**Comment by spalladino** [comment]
Hey @brooklynbagel, I'm not sure I understand the question. The snippet you share below does not need the internal random value used in the signature algorithm. The point here is that, regardless of which of the many valid signatures you feed into that script, the recovered address will always be the same.
