### ISSUE TITLE
Retrieving a proposal status and archiving

### ISSUE THREAD

**Issue by shahnami** [OpenZeppelin/defender-client#63]
Defender-client currently doesn't have endpoints to archive or retrieve the status of a proposal. 

This is something that has been requested on the [forums](https://forum.openzeppelin.com/t/how-can-i-archive-or-check-the-status-of-proposals-using-defender-api/23997).

**Comment by mverzilli** [comment]
Moved to https://github.com/OpenZeppelin/defender/issues/2405
