### ISSUE TITLE
Update CreateSentinelRequest type to fit with multiple addresses sentinel

### ISSUE THREAD

**Issue by ernestognw** [OpenZeppelin/defender-client#80]
Found by @mok0203

Reference

> Using the UI, I was able to successfully create a Sentinel monitoring multiple contracts and it behaved as expected. 
> 
> Using the API, I was able to read multiple addresses, but I was not able to update (though it is possible this is operator error). Looking at the docs, it seems like the CreateSentinelRequest type should be updated to required addresses rather than address and required an array for the value. See:
>
> ![image](https://user-images.githubusercontent.com/33379285/157282179-feaeda8a-d467-4397-8035-2c9edff5d9b1.png)

> Couple considerations:
> 
> 1. Existing sentinels using the address parameter
> 
> I think this is being managed correctly with: https://github.com/OpenZeppelin/defender/commit/2296d7e4c230cc508a7a72ea9969c797b28c6356#diff-f586052a79139fb7fb0b3613c80f34cd213f051bf8cd073eb2da125267782de5R87
> 
> 2. Technically, there could be notification message body templates out there referencing sentinel.address that could theoretically break (at least for new sentinels created with multiple addresses). There is no reference to that param in our default template, so I don’t think it’s likely this is an issue. 
> 
> That said, I think there is always 1 address that triggered the issue, which we could just go ahead and cast to sentinel.address. I put that questions to @Dylan Kilkenny here: https://github.com/OpenZeppelin/defender/commit/2296d7e4c230cc508a7a72ea9969c797b28c6356#r68182905

**Comment by ernestognw** [comment]
Closed in favor of having issues in defender main repo

**Comment by dylan** [comment]
Wrong @dylan 🤙

**Comment by ernestognw** [comment]
> Wrong @dylan 🤙

lol, sorry sir
