### ISSUE TITLE
Accept updated fields only in update methods

### ISSUE THREAD

**Issue by mok0230** [OpenZeppelin/defender-client#83]
In sentinel `defender-sentinel-client`, the update method is currently invoked with the `id` and a complete [CreateSentinelRequest object](https://docs.openzeppelin.com/defender/sentinel-api-reference#create-endpoint). 

However, the only data it actually requires are the `id` and the specific fields to be updated. This would be a simpler API for consumers to utilize and it should be straightforward to make backwards compatible (as the full `CreateSentinelRequest` object is still a valid input).

With this way, a sentinel could be updated with simply:

```javascript
await client.update('foo', { paused: true })
```

There may be other packages that have similar APIs and these should probably all be in line with each other.

**Comment by shahnami** [comment]
Fixed by https://github.com/OpenZeppelin/defender-client/pull/84

**Comment by mok0230** [comment]
That's some quick work! Many thanks @shahnami
