### ISSUE TITLE
Verifying defender contracts

### ISSUE THREAD

**Issue by LukeSamkharadze** [OpenZeppelin/defender-client#88]
Hello, I just deployed multisafe contract from defender on `BSC` testnet, but I want it to be verified how can that be done?

**Comment by mverzilli** [comment]
Hi Luke, what network did you deploy it too? If it's one of the officially supported networks you can just go to app.gnosis-safe.io and try to import it there. If it works, it means it was created by the official proxy factory.

**Comment by LukeSamkharadze** [comment]
@mverzilli I deloyed it to `BSC` testnet.

How will importing in `app.gnosis-safe.io` will verify the contract?

I needed verification for the security audit

**Comment by mverzilli** [comment]
Hey, sorry, I misread your question. Unfortunately, at the moment there's no automated way to do that from Defender but I'll get back to you with some instructions and/or code to get it done. Would that work for you?

**Comment by LukeSamkharadze** [comment]
Cool, I would greatly appreciate that

**Comment by mverzilli** [comment]
Hey @LukeSamkharadze, I'll reply in the forum which is the right place for this conversation.
